spring.application.name=hotel-booking

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/hotel_booking_db?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
# Change based on your valid MySQL password.

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT Configuration
jwt.secret=7d86f7267a14f63c4c3b6c50711cc316a3c9be083e911eb3f9d51e89ce896860
jwt.expiration=86400000

# Mail Configuration (Example for Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=pooveshanmugam@gmail.com
spring.mail.password=qrohxpgloomcegey
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

# Logging
logging.level.org.springframework.web=INFO
logging.level.com.hcl.hotelbooking=DEBUG
